import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { motion } from "framer-motion";
import toast from "react-hot-toast";
import { useAuthStore } from "../store/auth.store";
import { useAppStore } from "../store/app.store";

const API = "/api/v1";

export function LoginPage() {
  const navigate   = useNavigate();
  const { setAuth } = useAuthStore();
  const { setDoctorId } = useAppStore();

  const [tab,      setTab]      = useState<"login" | "register">("login");
  const [loading,  setLoading]  = useState(false);

  const [loginForm,  setLoginForm]  = useState({ email: "", password: "" });
  const [regForm,    setRegForm]    = useState({
    doctor_id: "", email: "", full_name: "", specialisation: "", password: "", confirm: "",
  });

  const handleLogin = async () => {
    if (!loginForm.email || !loginForm.password) {
      toast.error("Enter email and password"); return;
    }
    setLoading(true);
    try {
      const body = new URLSearchParams({
        username: loginForm.email,
        password: loginForm.password,
      });
      const res  = await fetch(`${API}/auth/login`, {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body,
      });
      const text = await res.text();
      let data: any = {};
      try { data = JSON.parse(text); } catch { throw new Error(`Server error (${res.status}) — check backend is running`); }
      if (!res.ok) throw new Error(data.detail || "Login failed");
      setAuth(data.access_token, data.doctor_id, data.full_name, data.email, data.specialisation);
      setDoctorId(data.doctor_id);
      toast.success(`Welcome back, ${data.full_name}`);
      navigate("/");
    } catch (e: any) {
      toast.error(e.message);
    } finally {
      setLoading(false);
    }
  };

  const handleRegister = async () => {
    if (!regForm.doctor_id || !regForm.email || !regForm.full_name || !regForm.password) {
      toast.error("Fill all required fields"); return;
    }
    if (regForm.password !== regForm.confirm) {
      toast.error("Passwords do not match"); return;
    }
    if (regForm.password.length < 8) {
      toast.error("Password must be at least 8 characters"); return;
    }
    setLoading(true);
    try {
      const res  = await fetch(`${API}/auth/register`, {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify({
          doctor_id:      regForm.doctor_id,
          email:          regForm.email,
          full_name:      regForm.full_name,
          specialisation: regForm.specialisation || null,
          password:       regForm.password,
        }),
      });
      const text2 = await res.text();
      let data: any = {};
      try { data = JSON.parse(text2); } catch { throw new Error(`Server error (${res.status}) — check backend is running`); }
      if (!res.ok) throw new Error(data.detail || "Registration failed");
      setAuth(data.access_token, data.doctor_id, data.full_name, data.email, data.specialisation);
      setDoctorId(data.doctor_id);
      toast.success(`Account created — welcome, ${data.full_name}`);
      navigate("/");
    } catch (e: any) {
      toast.error(e.message);
    } finally {
      setLoading(false);
    }
  };

  const inputStyle = {
    width: "100%", padding: "10px 14px", fontSize: 14,
    border: "1px solid #e2e8f0", borderRadius: 8,
    color: "#0f172a", background: "#fff", boxSizing: "border-box" as const,
  };
  const labelStyle = { fontSize: 12, color: "#64748b", marginBottom: 4, display: "block" };

  return (
    <div style={{
      minHeight: "100vh", display: "flex",
      fontFamily: "system-ui, -apple-system, sans-serif",
    }}>
      {/* Left panel */}
      <div style={{
        width: 420, background: "#0f172a", color: "#e2e8f0",
        display: "flex", flexDirection: "column", padding: "48px 40px",
        justifyContent: "space-between",
      }}>
        <div>
          <div style={{ fontSize: 10, letterSpacing: "0.12em", color: "#64748b", marginBottom: 8 }}>
            COGNIZANT TECHNOVERSE 2026
          </div>
          <div style={{ fontSize: 28, fontWeight: 700, color: "#f1f5f9", marginBottom: 6 }}>
            VaidyaScribe
          </div>
          <div style={{ fontSize: 14, color: "#94a3b8", lineHeight: 1.6 }}>
            Tamil/English AI clinical scribe.<br />
            DPDP 2023 compliant · $0 cost.
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          {[
            { icon: "🎙", text: "30-second transcription via Groq Whisper" },
            { icon: "📋", text: "SOAP notes generated by Llama 3.1" },
            { icon: "🔍", text: "Hallucination safety gate on every note" },
            { icon: "🔒", text: "Your patients — only you can view them" },
          ].map(f => (
            <div key={f.text} style={{ display: "flex", gap: 12, alignItems: "flex-start" }}>
              <span style={{ fontSize: 18 }}>{f.icon}</span>
              <span style={{ fontSize: 13, color: "#94a3b8", lineHeight: 1.5 }}>{f.text}</span>
            </div>
          ))}
        </div>

        <div style={{ fontSize: 11, color: "#334155" }}>
          LangGraph · Whisper · NLLB-200 · Llama 3.1
        </div>
      </div>

      {/* Right panel — form */}
      <div style={{
        flex: 1, background: "#f8fafc",
        display: "flex", alignItems: "center", justifyContent: "center", padding: 40,
      }}>
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          style={{
            background: "#fff", borderRadius: 16,
            border: "1px solid #e2e8f0", padding: "36px 36px",
            width: "100%", maxWidth: 420,
            boxShadow: "0 4px 24px rgba(0,0,0,0.06)",
          }}
        >
          {/* Tabs */}
          <div style={{ display: "flex", gap: 4, marginBottom: 28,
            background: "#f1f5f9", padding: 4, borderRadius: 10 }}>
            {(["login", "register"] as const).map(t => (
              <button key={t} onClick={() => setTab(t)} style={{
                flex: 1, padding: "8px 0", borderRadius: 7, border: "none",
                fontSize: 13, fontWeight: 500, cursor: "pointer",
                background: tab === t ? "#fff" : "transparent",
                color: tab === t ? "#0f172a" : "#64748b",
                boxShadow: tab === t ? "0 1px 3px rgba(0,0,0,0.08)" : "none",
              }}>
                {t === "login" ? "Sign in" : "Register"}
              </button>
            ))}
          </div>

          {tab === "login" ? (
            <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
              <div style={{ fontSize: 18, fontWeight: 600, color: "#0f172a", marginBottom: 4 }}>
                Welcome back
              </div>
              <div>
                <label style={labelStyle}>Email address</label>
                <input style={inputStyle} type="email" placeholder="doctor@hospital.com"
                  value={loginForm.email}
                  onChange={e => setLoginForm(f => ({ ...f, email: e.target.value }))}
                  onKeyDown={e => e.key === "Enter" && handleLogin()} />
              </div>
              <div>
                <label style={labelStyle}>Password</label>
                <input style={inputStyle} type="password" placeholder="••••••••"
                  value={loginForm.password}
                  onChange={e => setLoginForm(f => ({ ...f, password: e.target.value }))}
                  onKeyDown={e => e.key === "Enter" && handleLogin()} />
              </div>
              <button onClick={handleLogin} disabled={loading} style={{
                background: "#0f172a", color: "#fff", border: "none",
                borderRadius: 10, padding: "12px", fontSize: 15,
                fontWeight: 500, cursor: loading ? "not-allowed" : "pointer",
                marginTop: 4,
              }}>
                {loading ? "Signing in..." : "Sign in →"}
              </button>
              <div style={{ fontSize: 12, color: "#94a3b8", textAlign: "center" }}>
                No account yet?{" "}
                <span onClick={() => setTab("register")}
                  style={{ color: "#3b82f6", cursor: "pointer" }}>
                  Register here
                </span>
              </div>
            </div>
          ) : (
            <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
              <div style={{ fontSize: 18, fontWeight: 600, color: "#0f172a", marginBottom: 4 }}>
                Create your account
              </div>
              {[
                { label: "Doctor ID *", key: "doctor_id", placeholder: "DR-001", type: "text" },
                { label: "Full name *",  key: "full_name",  placeholder: "Dr. Priya Sharma", type: "text" },
                { label: "Email address *", key: "email", placeholder: "doctor@hospital.com", type: "email" },
                { label: "Specialisation", key: "specialisation", placeholder: "Cardiology (optional)", type: "text" },
                { label: "Password *",  key: "password",  placeholder: "Min 8 characters", type: "password" },
                { label: "Confirm password *", key: "confirm", placeholder: "••••••••", type: "password" },
              ].map(f => (
                <div key={f.key}>
                  <label style={labelStyle}>{f.label}</label>
                  <input style={inputStyle} type={f.type} placeholder={f.placeholder}
                    value={(regForm as any)[f.key]}
                    onChange={e => setRegForm(r => ({ ...r, [f.key]: e.target.value }))} />
                </div>
              ))}
              <button onClick={handleRegister} disabled={loading} style={{
                background: "#0f172a", color: "#fff", border: "none",
                borderRadius: 10, padding: "12px", fontSize: 15,
                fontWeight: 500, cursor: loading ? "not-allowed" : "pointer",
                marginTop: 4,
              }}>
                {loading ? "Creating account..." : "Create account →"}
              </button>
            </div>
          )}
        </motion.div>
      </div>
    </div>
  );
}
